# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: macos-11 # Attempt to specify macOS 11 to get Swift 5.7.1 (you may need to check which macOS version has the Swift version you need)

    steps:
    - uses: actions/checkout@v3
    - name: Set Swift version
      run: echo "SWIFT_VERSION=5.7.1" >> $GITHUB_ENV
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
