# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.5.app/Contents/Developer'  # Change this to the Xcode version that includes Swift 5.8.0
    
    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
