name: Swift

on:
  push:
    branches: [ main ]  # Replace 'main' with the name of your default branch if it's different

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print directory structure
      run: ls -R
    - name: Build TribusDAmour
      run: swift build --target TribusDAmour -v
    - name: Run tests for TribusDAmour
      run: swift test --filter TribusDAmour -v
