name: Swift

on:
  push:
    branches: [ main ]  # Replace with your default branch if different

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print directory structure
      run: ls -R
    - name: Build
      run: swift build --target TribusDAmour -v
