# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2  # Updated from v3 to v2 as v2 is the latest stable version as of my last update

    # Remove or comment out this section if it's causing errors
    #- name: Set Xcode version
    #  run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer' 

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
