jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: List directory
        run: ls -R
      - name: Build the project
        run: swift build --target TribusDAmour -v
